# -*- coding: utf-8 -*-
"""cv_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDbAkDf-0f0MNOSJprzfl1Kvlv9p0C2w
"""

# -------------------------------
# SEGMENT 1 — Install & Download
# -------------------------------

!pip install kagglehub tensorflow matplotlib scikit-learn

import kagglehub
import os

# Download from Kaggle
path = kagglehub.dataset_download("jiayuanchengala/aid-scene-classification-datasets")
print("Dataset downloaded to:", path)

# Detect dataset root (AID has 30 folders)
def find_dataset_root(start_path):
    for root, dirs, files in os.walk(start_path):
        if len(dirs) >= 25:
            return root
    return start_path

data_dir = find_dataset_root(path)
print("AID dataset root:", data_dir)

# -------------------------------
# SEGMENT 2 — Data Generators
# -------------------------------

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = 224
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1/255.0,
    validation_split=0.25,
    rotation_range=25,
    zoom_range=0.2,
    horizontal_flip=True,
    vertical_flip=True
)

test_datagen = ImageDataGenerator(
    rescale=1/255.0,
    validation_split=0.25
)

train_gen = train_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training"
)

val_gen = test_datagen.flow_from_directory(
    data_dir,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation",
    shuffle=False
)

num_classes = len(train_gen.class_indices)
class_names = list(train_gen.class_indices.keys())
print("Classes:", class_names)

# -------------------------------
# SEGMENT 3 — Build Model
# -------------------------------

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model

base_model = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

base_model.trainable = False   # freeze backbone

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
output = Dense(num_classes, activation="softmax")(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0008),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# -------------------------------
# SEGMENT 4 — Training
# -------------------------------

EPOCHS = 12

history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS
)

# -------------------------------
# SEGMENT 5 — Evaluate
# -------------------------------

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

val_gen.reset()
preds = model.predict(val_gen)

y_pred = np.argmax(preds, axis=1)
y_true = val_gen.classes

print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, target_names=class_names))

# -------------------------------
# SEGMENT 6 — Confusion Matrix Plot
# -------------------------------

import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(22, 22))
sns.heatmap(cm, annot=False, cmap="Blues", square=True,
            xticklabels=class_names, yticklabels=class_names)

plt.title("Confusion Matrix — MobileNetV2 on AID-30", fontsize=18)
plt.xlabel("Predicted", fontsize=16)
plt.ylabel("True", fontsize=16)
plt.show()

# -------------------------------
# SEGMENT 7 — Plot Accuracy & Loss
# -------------------------------

plt.figure(figsize=(12, 5))

# Accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='train acc')
plt.plot(history.history['val_accuracy'], label='val acc')
plt.title('Accuracy')
plt.legend()

# Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='train loss')
plt.plot(history.history['val_loss'], label='val loss')
plt.title('Loss')
plt.legend()

plt.show()
